package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 2:09:50 PM by Hibernate Tools 5.4.14.Final

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private String username;
	private String password;
	private Boolean status;
	private Integer mssv;

	public Account() {
	}

	public Account(String username) {
		this.username = username;
	}

	public Account(String username, String password, Boolean status, Integer mssv) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.mssv = mssv;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Integer getMssv() {
		return this.mssv;
	}

	public void setMssv(Integer mssv) {
		this.mssv = mssv;
	}

}
