package myproject.QuanLySinhVien.entities;
// Generated Jun 17, 2020 9:35:42 AM by Hibernate Tools 5.4.14.Final

/**
 * DiemSo generated by hbm2java
 */
public class DiemSo implements java.io.Serializable {

	private DiemSoId id;
	private HocSinh hocSinh;
	private MonHoc monHoc;
	private Float diemGk;
	private Float diemCk;
	private Float diemKhac;
	private Float diemTong;

	public DiemSo() {
	}

	public DiemSo(DiemSoId id, HocSinh hocSinh, MonHoc monHoc) {
		this.id = id;
		this.hocSinh = hocSinh;
		this.monHoc = monHoc;
	}

	public DiemSo(DiemSoId id, HocSinh hocSinh, MonHoc monHoc, Float diemGk, Float diemCk, Float diemKhac,
			Float diemTong) {
		this.id = id;
		this.hocSinh = hocSinh;
		this.monHoc = monHoc;
		this.diemGk = diemGk;
		this.diemCk = diemCk;
		this.diemKhac = diemKhac;
		this.diemTong = diemTong;
	}

	public DiemSoId getId() {
		return this.id;
	}

	public void setId(DiemSoId id) {
		this.id = id;
	}

	public HocSinh getHocSinh() {
		return this.hocSinh;
	}

	public void setHocSinh(HocSinh hocSinh) {
		this.hocSinh = hocSinh;
	}

	public MonHoc getMonHoc() {
		return this.monHoc;
	}

	public void setMonHoc(MonHoc monHoc) {
		this.monHoc = monHoc;
	}

	public Float getDiemGk() {
		return this.diemGk;
	}

	public void setDiemGk(Float diemGk) {
		this.diemGk = diemGk;
	}

	public Float getDiemCk() {
		return this.diemCk;
	}

	public void setDiemCk(Float diemCk) {
		this.diemCk = diemCk;
	}

	public Float getDiemKhac() {
		return this.diemKhac;
	}

	public void setDiemKhac(Float diemKhac) {
		this.diemKhac = diemKhac;
	}

	public Float getDiemTong() {
		return this.diemTong;
	}

	public void setDiemTong(Float diemTong) {
		this.diemTong = diemTong;
	}

}
