package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 2:09:50 PM by Hibernate Tools 5.4.14.Final

/**
 * DiemSoId generated by hbm2java
 */
public class DiemSoId implements java.io.Serializable {

	private String maMh;
	private int mssv;

	public DiemSoId() {
	}

	public DiemSoId(String maMh, int mssv) {
		this.maMh = maMh;
		this.mssv = mssv;
	}

	public String getMaMh() {
		return this.maMh;
	}

	public void setMaMh(String maMh) {
		this.maMh = maMh;
	}

	public int getMssv() {
		return this.mssv;
	}

	public void setMssv(int mssv) {
		this.mssv = mssv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiemSoId))
			return false;
		DiemSoId castOther = (DiemSoId) other;

		return ((this.getMaMh() == castOther.getMaMh()) || (this.getMaMh() != null && castOther.getMaMh() != null
				&& this.getMaMh().equals(castOther.getMaMh()))) && (this.getMssv() == castOther.getMssv());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaMh() == null ? 0 : this.getMaMh().hashCode());
		result = 37 * result + this.getMssv();
		return result;
	}

}
