package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 2:09:50 PM by Hibernate Tools 5.4.14.Final

/**
 * HocSinh generated by hbm2java
 */
public class HocSinh implements java.io.Serializable {

	private int mssv;
	private String hoTen;
	private boolean gioiTinh;
	private int cmnd;
	private String maLop;

	public HocSinh() {
	}

	public HocSinh(int mssv, String hoTen, boolean gioiTinh, int cmnd, String maLop) {
		this.mssv = mssv;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.cmnd = cmnd;
		this.maLop = maLop;
	}

	public int getMssv() {
		return this.mssv;
	}

	public void setMssv(int mssv) {
		this.mssv = mssv;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public int getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(int cmnd) {
		this.cmnd = cmnd;
	}

	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

}
