package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 10:12:58 PM by Hibernate Tools 5.4.14.Final

/**
 * LopHoc generated by hbm2java
 */
public class LopHoc implements java.io.Serializable {

	private String maLop;

	public LopHoc() {
	}

	public LopHoc(String maLop) {
		this.maLop = maLop;
	}

	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

}
