package myproject.QuanLySinhVien.entities;
// Generated Jun 17, 2020 9:35:42 AM by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MonHoc generated by hbm2java
 */
public class MonHoc implements java.io.Serializable {

	private String maMon;
	private String tenMon;
	private String phongHoc;
	private Set lopHocs = new HashSet(0);
	private Set phucKhaos = new HashSet(0);
	private Set diemSos = new HashSet(0);

	public MonHoc() {
	}

	public MonHoc(String maMon, String tenMon, String phongHoc) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
	}

	public MonHoc(String maMon, String tenMon, String phongHoc, Set lopHocs, Set phucKhaos, Set diemSos) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
		this.lopHocs = lopHocs;
		this.phucKhaos = phucKhaos;
		this.diemSos = diemSos;
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

	public Set getLopHocs() {
		return this.lopHocs;
	}

	public void setLopHocs(Set lopHocs) {
		this.lopHocs = lopHocs;
	}

	public Set getPhucKhaos() {
		return this.phucKhaos;
	}

	public void setPhucKhaos(Set phucKhaos) {
		this.phucKhaos = phucKhaos;
	}

	public Set getDiemSos() {
		return this.diemSos;
	}

	public void setDiemSos(Set diemSos) {
		this.diemSos = diemSos;
	}

}
