package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 10:12:58 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;

/**
 * MonHoc generated by hbm2java
 */
public class MonHoc implements java.io.Serializable {

	private String maMon;
	private String tenMon;
	private String phongHoc;
	private boolean phucKhao;
	private Date deadLine;

	public MonHoc() {
	}

	public MonHoc(String maMon, String tenMon, String phongHoc, boolean phucKhao) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
		this.phucKhao = phucKhao;
	}

	public MonHoc(String maMon, String tenMon, String phongHoc, boolean phucKhao, Date deadLine) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
		this.phucKhao = phucKhao;
		this.deadLine = deadLine;
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

	public boolean isPhucKhao() {
		return this.phucKhao;
	}

	public void setPhucKhao(boolean phucKhao) {
		this.phucKhao = phucKhao;
	}

	public Date getDeadLine() {
		return this.deadLine;
	}

	public void setDeadLine(Date deadLine) {
		this.deadLine = deadLine;
	}

}
