package myproject.QuanLySinhVien.entities;
// Generated Jun 17, 2020 11:17:35 PM by Hibernate Tools 5.4.14.Final

/**
 * MonHoc generated by hbm2java
 */
public class MonHoc implements java.io.Serializable {

	private String maMon;
	private String tenMon;
	private String phongHoc;

	public MonHoc() {
	}

	public MonHoc(String maMon, String tenMon, String phongHoc) {
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

}
