package myproject.QuanLySinhVien.entities;
// Generated Jun 21, 2020 10:12:58 PM by Hibernate Tools 5.4.14.Final

/**
 * PhucKhaoId generated by hbm2java
 */
public class PhucKhaoId implements java.io.Serializable {

	private int mssv;
	private String maMh;

	public PhucKhaoId() {
	}

	public PhucKhaoId(int mssv, String maMh) {
		this.mssv = mssv;
		this.maMh = maMh;
	}

	public int getMssv() {
		return this.mssv;
	}

	public void setMssv(int mssv) {
		this.mssv = mssv;
	}

	public String getMaMh() {
		return this.maMh;
	}

	public void setMaMh(String maMh) {
		this.maMh = maMh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhucKhaoId))
			return false;
		PhucKhaoId castOther = (PhucKhaoId) other;

		return (this.getMssv() == castOther.getMssv())
				&& ((this.getMaMh() == castOther.getMaMh()) || (this.getMaMh() != null && castOther.getMaMh() != null
						&& this.getMaMh().equals(castOther.getMaMh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMssv();
		result = 37 * result + (getMaMh() == null ? 0 : this.getMaMh().hashCode());
		return result;
	}

}
