package myproject.QuanLySinhVien.entities;
// Generated Jun 17, 2020 11:17:35 PM by Hibernate Tools 5.4.14.Final

/**
 * ThoiKhoaBieuId generated by hbm2java
 */
public class ThoiKhoaBieuId implements java.io.Serializable {

	private String maMon;
	private String maLop;

	public ThoiKhoaBieuId() {
	}

	public ThoiKhoaBieuId(String maMon, String maLop) {
		this.maMon = maMon;
		this.maLop = maLop;
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getMaLop() {
		return this.maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThoiKhoaBieuId))
			return false;
		ThoiKhoaBieuId castOther = (ThoiKhoaBieuId) other;

		return ((this.getMaMon() == castOther.getMaMon()) || (this.getMaMon() != null && castOther.getMaMon() != null
				&& this.getMaMon().equals(castOther.getMaMon())))
				&& ((this.getMaLop() == castOther.getMaLop()) || (this.getMaLop() != null
						&& castOther.getMaLop() != null && this.getMaLop().equals(castOther.getMaLop())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaMon() == null ? 0 : this.getMaMon().hashCode());
		result = 37 * result + (getMaLop() == null ? 0 : this.getMaLop().hashCode());
		return result;
	}

}
