package myproject.QuanLySinhVien.entities;
// Generated Jun 17, 2020 11:17:35 PM by Hibernate Tools 5.4.14.Final

/**
 * ThoiKhoaBieu generated by hbm2java
 */
public class ThoiKhoaBieu implements java.io.Serializable {

	private ThoiKhoaBieuId id;

	public ThoiKhoaBieu() {
	}

	public ThoiKhoaBieu(ThoiKhoaBieuId id) {
		this.id = id;
	}

	public ThoiKhoaBieuId getId() {
		return this.id;
	}

	public void setId(ThoiKhoaBieuId id) {
		this.id = id;
	}

}
